project_id = "attczdhexkpxpyqyasgz"

[functions.create-admin]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.woocommerce-sync]
verify_jwt = false

[functions.stallion-express]
verify_jwt = true

[functions.send-abandoned-cart-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-shipping-notification]
verify_jwt = false