project_id = "attczdhexkpxpyqyasgz"

[functions.link-woocommerce-customer]
verify_jwt = true

[functions.flag-orders-for-review]
verify_jwt = false

[functions.fix-order-unit-prices]
verify_jwt = false

[functions.backfill-fulfilled-timestamps]
verify_jwt = true

[functions.check-order-integrity]
verify_jwt = false

[functions.track-visitor]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.woocommerce-sync]
verify_jwt = false

[functions.stallion-express]
verify_jwt = true

[functions.send-abandoned-cart-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-shipping-notification]
verify_jwt = true

[functions.optimize-homepage-images]
verify_jwt = false

[functions.sync-stallion-tracking]
verify_jwt = true

[functions.calculate-shipping-zones]
verify_jwt = false

[functions.fix-order-shipping]
verify_jwt = false

[functions.create-refund]
verify_jwt = true

[functions.create-bulk-refund]
verify_jwt = true

[functions.backfill-payment-intents]
verify_jwt = true

[functions.chitchats-shipping]
verify_jwt = false

[functions.add-first-sister-story]
verify_jwt = false

[functions.fix-product-images]
verify_jwt = false

[functions.reorder-sister-story]
verify_jwt = false

